### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by swilmet** [BYVoid/uchardet#10]
There is no tags in git, and it seems that there is no releases. The version is currently the 0.0.1, so at a first glance it looks like the project is very young and has just started, but the first commit was created in 2011. It's maybe time to create a real release.

**Comment by Jehan** [comment]
Adding a note: some software are willing to add a dependency to it. Not having a proper release may be a blocker. Thanks!

**Comment by swilmet** [comment]
Is uchardet unmaintained?

**Comment by Jehan** [comment]
Well if there are no answers, I'd be willing to take the maintenance. It does not make me particularly ecstatic because I can hardly make that much time, but the subject of good internationalization is important to me.

**Comment by BYVoid** [comment]
@Jehan. It would be perfect if you would like to maintain it. Added you as the maintainer.

**Comment by Jehan** [comment]
@BYVoid Awesome, thanks!

I will happily co-maintain so that we can use this lib in various software. :-)
I don't plan on actively *developing* the lib, but at least maintain it and integrate third-party patches… at the very least until someone proposes an alternative which would work better.

For info, someone is currently packaging [uchardet into Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1264713), and it is already packaged into other distrib.
Thanks for this!
