### ISSUE TITLE
Needs updated to the current Mozilla code

### ISSUE THREAD

**Issue by yurivict** [BYVoid/uchardet#3]
Mozilla people say that uchardet code is 3 years old (https://bugzilla.mozilla.org/show_bug.cgi?id=1105839).

**Comment by Jehan** [comment]
> Mozilla people say that uchardet code is 3 years old

This is actually not what they are really saying in this report. They are rather saying that they don't really use the universal detector anymore in Firefox (though they seem to keep the code around), but per-language detectors (which is "hinting" then basically, but probably stronger).

I've searched recent code. Nowadays, it seems to be there:
http://hg.mozilla.org/mozilla-central/file/tip/extensions/universalchardet/

I can see some newer commits indeed, but there does not seem to have had real improvement for years. I see a commit removing encoding detectors that they don't use anymore, and they also updated the license from MPL 1.1/GPL 2.0/LGPL 2.1 to MPL v. 2.0 (which may be a problem for us, I don't know?).
Anyway we could study more of the differences, but I'm not sure that there would be much to merge (if at all, because of the license change).

**Comment by Jehan** [comment]
I checked Mozilla code today. It does not seem as the universal chardet implementation has received any love for years. Nowadays uchardet has a proper build, is more efficient, has about a dozen more (language, encoding) couple supported and an architecture to easily create new supports. I'm not sure if there still is any reason to continue monitoring universal chardet when they clearly say they have abandoned this.

Nevertheless if anyone detects new commits from Mozilla which are worth looking into, don't hesitate to ping me! :-)
https://bugs.freedesktop.org/enter_bug.cgi?product=uchardet

You are more than welcome to report other bugs or contribute patches too!
