### ISSUE TITLE
Cast unsigned int

### ISSUE THREAD

**Issue by marinofaggiana** [BYVoid/uchardet#37]
On : 

> PRBool nsCharSetProber::FilterWithoutEnglishLetters(const char* aBuf, PRUint32 aLen, char** newBuf, PRUint32& newLen)

&

> PRBool nsCharSetProber::FilterWithEnglishLetters(const char* aBuf, PRUint32 aLen, char** newBuf, PRUint32& newLen)

Cast : 

newLen = (unsigned int)(newptr - *newBuf);

**Comment by Jehan** [comment]
Thanks. I don't get any compilation warning or anything, but obviously this makes sense, so let's do it.
I casted to PRUint32 instead (which is the same as unsigned int since it's a typedef but it's more proper to do it this way).
Next time, just send me a patch, then you get proper authorship. :-)
Also, I'm sure you already know since I told you, and you do it on purpose because you know I still monitor here, but I would prefer if you reported bugs on Freedesktop's bug tracker. :P
See the page: https://www.freedesktop.org/wiki/Software/uchardet/

In any case, thanks again!

commit 1898847eb69b581731c4a735bfb3a77ef4238012
Author: Jehan <jehan@girinstud.io>
Date:   Sun Aug 27 13:01:30 2017 +0200

    src: cast value to its proper type.
    
    Thanks to Marino Faggiana for reporting it.
    See: https://github.com/BYVoid/uchardet/issues/37

 src/nsCharSetProber.cpp | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
